[build]
  command = "ng build --configuration production"
  publish = "dist/candidato-web/browser"

[build.environment]
  NETLIFY_USE_ANGULAR_RUNTIME = "false"
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/angular-runtime"
  
  [plugins.inputs]
    toBeEnabled = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200