
[build]
  command = "ng build --configuration production"
  publish = "dist/candidato-web/browser"

[[plugins]]
  package = "@netlify/angular-runtime"
  [plugins.inputs]
    toBeEnabled = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200