[build]
  command = "ng build --configuration production"
  publish = "dist/candidato-web/browser"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_USE_ANGULAR_RUNTIME = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200